# Header
menu:
  首页: /
  存档: /archives
  html: /categories/html
  css: /categories/css
  javascript: /categories/jascript
  nodejs: /nodejs

# rss: /atom.xml

# Content
excerpt_link: 阅读更多
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
# - tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id: